const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const root=path.resolve(__dirname,'../..');let chromium;
for(const dir of fs.readdirSync(path.join(process.env.LOCALAPPDATA,'npm-cache/_npx'))){try{chromium=require(path.join(process.env.LOCALAPPDATA,'npm-cache/_npx',dir,'node_modules/playwright')).chromium;break;}catch{}}
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript','.css':'text/css','.json':'application/json','.wav':'audio/wav','.mp3':'audio/mpeg'};
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(e,b)=>{if(e){res.writeHead(404).end();return;}res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream','Content-Length':b.length}).end(b);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch();const errors=[];
try{const page=await browser.newPage({viewport:{width:1600,height:1000}});page.on('pageerror',e=>errors.push(e.message));
await page.goto(base+'/games/silent-baton/presentation/index.html');await page.waitForFunction(()=>window.silentReady);
assert.equal(await page.locator('#stage button').count(),4);assert.equal(await page.locator('#review').isVisible(),false);assert.equal(await page.locator('audio').count(),0);
for(const piece of await page.locator('#piece option').evaluateAll(os=>os.map(o=>o.value))){await page.selectOption('#piece',piece);let steps=0;while(await page.locator('#review').isHidden()){await page.getByRole('button',{name:'박만 준다',exact:true}).click();assert.ok(++steps<=24);}assert.match(await page.locator('#reviewBody').innerText(),/점/);await page.getByRole('button',{name:'평론을 기억하고 다시 지휘하기'}).click();assert.equal(await page.locator('#previous').isVisible(),true);assert.equal(await page.locator('#review').isVisible(),false);}
await page.locator('#reset').click();assert.equal(await page.locator('#previous').isVisible(),false);await page.selectOption('#piece','p_overture');await page.getByRole('button',{name:'목관 선택',exact:true}).click();await page.getByRole('button',{name:'작게',exact:true}).click();assert.match(await page.locator('#status').innerText(),/목관/);
await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
await page.goto(base+'/games/mystery-blackwood/docs/voice-audition/index.html');assert.equal(await page.locator('article').count(),10);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
const media=await page.locator('audio').evaluateAll(async elements=>Promise.all(elements.map(a=>new Promise((resolve,reject)=>{a.onloadedmetadata=()=>resolve({duration:a.duration,src:a.src});a.onerror=()=>reject(Error(a.src));a.load();}))));assert.equal(media.length,20);assert.ok(media.every(m=>Number.isFinite(m.duration)&&m.duration>0));
const audios=page.locator('audio');await audios.nth(0).evaluate(a=>a.play());await audios.nth(1).evaluate(a=>a.play());assert.equal(await audios.nth(0).evaluate(a=>a.paused),true);
await page.setViewportSize({width:1600,height:1000});await page.screenshot({path:path.join(root,'games/mystery-blackwood/docs/voice-audition/preview.png')});
assert.deepEqual(errors,[]);const report={silentBaton:{pieces:3,completionAndReplay:true,mobileOverflow:false},voiceAudition:{samples:10,decodedAudioFiles:media.length,exclusivePlayback:true,mobileOverflow:false},pageErrors:errors};fs.writeFileSync(path.join(root,'docs/poc-gallery/takeover-browser.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
